### ISSUE TITLE
请教如何优雅的处理这种

### ISSUE THREAD

**Issue by tosslife** [starboychina/AlamofireSwiftyJSON#2]
接口想要返回的业务数据外总是“包裹”了一层状态数据来标记这一次业务返回的成功、失败以及失败的原因。
{
    "resultCode":200,
    "resultMsg":"查询成功!",
    "data":{
        "city":"北京",
        "temperature":"8℃~20℃",
        "weather":"晴转霾"
    }
}

或者 

{
    "resultCode":200,
    "resultMsg":"查询成功!",
    "data":[
        {
            "city":"北京",
            "temperature":"8℃~20℃",
            "weather":"晴转霾"
        },
        {
            "city":"南京",
            "temperature":"12℃~21℃",
            "weather":"晴"
        }
    ]
}

该如何封装呢

**Comment by Xinguang** [comment]
使用 HTTP状态码（HTTP Status Code）
https://zh.wikipedia.org/wiki/HTTP%E7%8A%B6%E6%80%81%E7%A0%81

HTTP状态码 在HTTP 头里, 并不在 Body 里
但当网络无法访问时,要特殊处理一下.
所以可以简化为

http Status Code:200
返回值为

``` json
{
"city":"北京",
"temperature":"8℃~20℃",
"weather":"晴转霾"
}
```

responseSwiftyJSON

``` swift
Alamofire.request(URL, method: .get, parameters: parameters).responseSwiftyJSON {
    result in
        //result.isSuccess == true //请求成功 (statusCode == 200~207,301,302 )
        //result.isFailure==true//请求失败
        //result.response==nil // 没有网络,超时等原因,导致没得到服务器响应
        //result.response?.statusCode//根据 statusCode 做出判断
        // 4xx资源错误 5xx 服务器处理错误
}
```
