### ISSUE TITLE
Extra Argument in call

### ISSUE THREAD

**Issue by anirudhamahale** [starboychina/AlamofireSwiftyJSON#3]
I get extra argument in call error.
In my Podfile I have 'AlamofireSwiftyJSON' and it installed Alamofire 4.2.0, AlamofireSwiftyJSON 0.2.0, SwiftyJSON 3.1.3 for me. 

I imported Alamofire, AlamofireSwiftyJSON in my swift file.
When I try to use it to make request, it give me this error.

![screen shot 2017-01-11 at 4 27 55 pm](https://cloud.githubusercontent.com/assets/16848003/21846092/6e86ca32-d81b-11e6-9014-2ef56048e183.png)

**Comment by Xinguang** [comment]
I'm Sorry, i forgot to update the README.

it's changed since alamofire 4.0.
https://github.com/Alamofire/Alamofire#http-methods
It's will be

```sh
Alamfire.request(URL, method: .get, parameters: ["foo": "bar"])
```

not

```sh
Alamofire.request(.GET, URL, parameters: ["foo": "bar"])
```

any more
